// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MadLibsGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("stories")]
        public Story[] Stories { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }
    }

    public partial class Story
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("template")]
        public string Template { get; set; }

        [JsonProperty("blanks")]
        public Blank[] Blanks { get; set; }

        [JsonProperty("blankCount")]
        public long BlankCount { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }
    }

    public partial class Blank
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }
    }
}
